services:
  database:
    image: mariadb:11
    restart: always
    ports:
    - "127.0.0.1:3306:3306"
    environment:
    - "MARIADB_USER=root"
    - "MARIADB_PASSWORD=root"
    - "MARIADB_ROOT_PASSWORD=root"
    - "MARIADB_DATABASE=bsf"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
    - "mariadb_data:/var/lib/mysql:Z"
volumes:
  mariadb_data: